// Code generated by python/agent_profiles_gen.py from
// configFiles/claude-code/profiles.yaml. DO NOT EDIT: edit the YAML and run
// `agent-profiles-sync`.
//
// Package profiles is the generated identity of each Claude Code seat. It
// carries literals rather than reading the YAML, which keeps this module free
// of dependencies and free of runtime file I/O.
package profiles

// SourceSHA256 is the digest of the YAML these tables came from. The test in
// this package recomputes it, so a hand-edited or stale generated file fails
// loudly instead of drifting.
const SourceSHA256 = "26f151e5630b08683628f0cf4b12171688aeec6dc2132ff8716543425e813974"

// Order is the seats in display order.
var Order = []string{"default", "work"}

// PickerColors maps a config home's basename to the SGR colour the session
// pickers paint that seat's rows. Which account a session belongs to is the
// thing worth seeing at a glance, since the whole point of resuming across
// seats is that they are otherwise interchangeable. A home with no entry gets
// no colour rather than a wrong one.
var PickerColors = map[string]string{
	".claude":      "235;145;60",
	".claude-work": "108;113;196",
}

// Markers maps a config home's basename to the seat's emoji.
var Markers = map[string]string{
	".claude":      "🦋",
	".claude-work": "🏫",
}
