#!/usr/bin/env python3
"""Generate the per-language profile tables from configFiles/claude-code/profiles.yaml.

The YAML is the single source of truth for the Claude Code seats. Nothing reads
it at runtime: parsing YAML costs about 30ms in python and 57ms in yq, and the
zsh tables are sourced by every interactive shell, so the consumers read
generated literals instead and pay nothing.

Three files are written, each recording the SHA-256 of the YAML so staleness is
detectable rather than remembered:

  zshlang/auto-load/others/claude-profiles.gen.zsh
  golang/agent_session/internal/profiles/profiles_gen.go
  configFiles/claude-code/profiles.gen.bash

Run it as `agent-profiles-sync`, or directly. It prints what it wrote, and with
--check it writes nothing and exits non-zero if any output is out of date, which
is what the Go test uses.
"""

import argparse
import hashlib
import pathlib
import sys

try:
    import yaml
except ImportError:  # pragma: no cover - a clear message beats a traceback
    sys.exit("agent_profiles_gen: PyYAML is required (pip install pyyaml)")

REPO = pathlib.Path(__file__).resolve().parent.parent
SOURCE = REPO / "configFiles/claude-code/profiles.yaml"

ZSH_OUT = REPO / "zshlang/auto-load/others/claude-profiles.gen.zsh"
GO_OUT = REPO / "golang/agent_session/internal/profiles/profiles_gen.go"
BASH_OUT = REPO / "configFiles/claude-code/profiles.gen.bash"

#: Which zsh table each per-profile field feeds, and the prose that goes above
#: it. The zsh names are load-bearing: they are what the launcher and the tmux
#: helpers already read, so they must not drift.
ZSH_TABLES = [
    ("marker", "claude_code_profile_markers", "One emoji per seat, for the tty title, the status line badge and the\ntmux pane label alike."),
    ("label", "claude_code_profile_labels", "The word a seat goes by where a cue has to spell it out."),
    ("color", "claude_code_profile_colors", "The seat's identity colour as an `R;G;B' triplet, for\n[agfi:h-claude-profile-color-hex] to hand to tmux. A seat with no entry\nhas no colour to give it."),
    ("tint", "claude_code_profile_tints", "The pane background each seat washes to. No entry, no tint."),
    ("border", "claude_code_profile_borders", "The tmux style attributes added on top of the seat's colour for its pane\nborder. No entry, no border."),
    ("theme", "claude_code_profile_themes", "Which tracked file under =configFiles/claude-code/themes/= a seat's\n=themes/profile.json= points at."),
]

BANNER_ZSH = """##
#: Generated by =python/agent_profiles_gen.py= from
#: =configFiles/claude-code/profiles.yaml=. DO NOT EDIT: edit the YAML and run
#: `agent-profiles-sync'. The prose explaining *why* each seat looks the way it
#: does lives in the YAML, next to the values.
#:
#: Literals rather than a parse, because every interactive shell sources this.
##
#: SHA-256 of the source, checked by =internal/profiles= in the Go module.
typeset -g claude_code_profiles_source_sha256='{sha}'
"""

BANNER_GO = """// Code generated by python/agent_profiles_gen.py from
// configFiles/claude-code/profiles.yaml. DO NOT EDIT: edit the YAML and run
// `agent-profiles-sync`.
//
// Package profiles is the generated identity of each Claude Code seat. It
// carries literals rather than reading the YAML, which keeps this module free
// of dependencies and free of runtime file I/O.
package profiles

// SourceSHA256 is the digest of the YAML these tables came from. The test in
// this package recomputes it, so a hand-edited or stale generated file fails
// loudly instead of drifting.
const SourceSHA256 = "{sha}"
"""


def load():
    raw = SOURCE.read_bytes()
    sha = hashlib.sha256(raw).hexdigest()
    doc = yaml.safe_load(raw)

    order = doc["order"]
    profiles = doc["profiles"]
    missing = [p for p in order if p not in profiles]
    if missing:
        sys.exit(f"agent_profiles_gen: order names unknown profiles: {missing}")
    extra = [p for p in profiles if p not in order]
    if extra:
        sys.exit(f"agent_profiles_gen: profiles missing from order: {extra}")
    for name in order:
        for required in ("home", "launcher", "marker", "label", "theme"):
            if not profiles[name].get(required):
                sys.exit(f"agent_profiles_gen: profile {name!r} has no {required!r}")

    return sha, order, profiles


def zsh_quote(s):
    #: Single quotes, with the only escape zsh needs inside them.
    return "'" + str(s).replace("'", "'\\''") + "'"


def render_zsh(sha, order, profiles):
    out = [BANNER_ZSH.format(sha=sha), ""]
    out.append("#: Iteration and display order; an associative array has none of its own.")
    out.append("typeset -ga claude_code_profile_order=( " + " ".join(order) + " )")

    for field, table, prose in ZSH_TABLES:
        out.append("#: " + prose.replace("\n", "\n#: "))
        out.append(f"typeset -gA {table}=(")
        width = max((len(n) for n in order), default=0)
        for name in order:
            value = profiles[name].get(field)
            if value is None:
                #: Commented rather than absent, so the convention that a
                #: missing entry means "no cue" stays visible in the table.
                out.append(f"    # {name.ljust(width)}  <none>")
            else:
                out.append(f"    {name.ljust(width)}  {zsh_quote(value)}")
        out.append(")")

    width = max((len(n) for n in order), default=0)

    out.append("#: The basename of each seat's config home, which is what a transcript's")
    out.append("#: path reveals and therefore how the pickers identify a seat.")
    out.append("typeset -gA claude_code_profile_homes=(")
    for name in order:
        out.append(f"    {name.ljust(width)}  {zsh_quote(profiles[name]['home'])}")
    out.append(")")

    out.append("#: A seat's =CLAUDE_CONFIG_DIR=, or the empty string for the one that needs")
    out.append("#: none. Everything else -- config file, Keychain service, cache dir --")
    out.append("#: derives from this. Double-quoted, so =${HOME}= expands at source time.")
    out.append("typeset -gA claude_code_profiles=(")
    for name in order:
        out.append(f"    {name.ljust(width)}  {config_dir(profiles[name])}")
    out.append(")")

    out.append("#: The command that starts each seat, for [agfi:claude-code-session-resume].")
    out.append("typeset -gA claude_code_profile_launchers=(")
    for name in order:
        out.append(f"    {name.ljust(width)}  {zsh_quote(profiles[name]['launcher'])}")
    out.append(")")
    return "\n".join(out) + "\n"


def config_dir(profile):
    #: Derived rather than declared: `.claude' is where Claude Code keeps its
    #: config with CLAUDE_CONFIG_DIR unset, so that seat exports nothing, and
    #: every other seat exports its home under $HOME. See the YAML.
    home = profile["home"]
    if home == ".claude":
        return "''"
    return f'"${{HOME}}/{home}"'


def picker_colors(order, profiles):
    #: Every seat gets a picker colour: `picker_color` when it has one, else
    #: its identity colour. A seat with neither is simply not painted.
    out = {}
    for name in order:
        p = profiles[name]
        colour = p.get("picker_color") or p.get("color")
        if colour:
            out[p["home"]] = colour
    return out


def render_go(sha, order, profiles):
    out = [BANNER_GO.format(sha=sha)]

    out.append("// Order is the seats in display order.")
    out.append("var Order = []string{" + ", ".join(f'"{n}"' for n in order) + "}")
    out.append("")
    #: gofmt aligns the values of a run of map entries into a column, so the
    #: generator has to as well, or every regeneration would differ from a
    #: gofmt-clean file and --check could never be satisfied.
    def go_map(name, doc, pairs):
        out.append(doc)
        out.append(f"var {name} = map[string]string{{")
        keys = {k: f'"{k}":' for k in pairs}
        width = max((len(v) for v in keys.values()), default=0)
        for k, v in pairs.items():
            out.append(f'\t{keys[k].ljust(width)} "{v}",')
        out.append("}")

    go_map(
        "PickerColors",
        "\n".join([
            "// PickerColors maps a config home's basename to the SGR colour the session",
            "// pickers paint that seat's rows. Which account a session belongs to is the",
            "// thing worth seeing at a glance, since the whole point of resuming across",
            "// seats is that they are otherwise interchangeable. A home with no entry gets",
            "// no colour rather than a wrong one.",
        ]),
        picker_colors(order, profiles),
    )
    out.append("")
    go_map(
        "Markers",
        "// Markers maps a config home's basename to the seat's emoji.",
        {profiles[n]["home"]: profiles[n]["marker"] for n in order},
    )
    return "\n".join(out) + "\n"


def render_bash(sha, order, profiles):
    #: Sourceable bash rather than JSON, because the only consumer is the
    #: status line, which is re-run on every render: an associative array costs
    #: it nothing, where a `jq' lookup would cost a fork of about 2.6ms.
    out = [
        "# Generated by python/agent_profiles_gen.py from",
        "# configFiles/claude-code/profiles.yaml. DO NOT EDIT: edit the YAML and run",
        "# `agent-profiles-sync`.",
        "#",
        "# Sourced by statusline.sh, which lives beside this file. Bash rather than",
        "# POSIX sh because the status line already requires bash, and an associative",
        "# array is one lookup with no subshell.",
        "#",
        "# SHA-256 of the source, checked by internal/profiles in the Go module.",
        f'claude_code_profiles_source_sha256="{sha}"',
        "",
        "# The seats, in display order, keyed by the basename of their config home.",
        "claude_code_profile_order=(" + " ".join(f'"{n}"' for n in order) + ")",
    ]

    def bash_map(name, doc, pairs):
        #: No alignment padding: bash reads a space after the `=' as the start
        #: of a new word and rejects the assignment.
        out.append("")
        out.append(doc)
        out.append(f"declare -A {name}=(")
        for k, v in pairs.items():
            out.append(f'    ["{k}"]="{v}"')
        out.append(")")

    bash_map(
        "claude_code_profile_names",
        "# Which seat a config home belongs to.",
        {profiles[n]["home"]: n for n in order},
    )
    bash_map(
        "claude_code_profile_markers",
        "# One emoji per seat, the same glyph the tty title and the tmux pane label\n"
        "# use. A config home with no entry is unregistered and gets no badge.",
        {profiles[n]["home"]: profiles[n]["marker"] for n in order},
    )
    bash_map(
        "claude_code_profile_labels",
        "# The word a seat goes by where a cue has to spell it out.",
        {profiles[n]["home"]: profiles[n]["label"] for n in order},
    )
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="write nothing; exit 1 if any output is stale")
    args = ap.parse_args()

    sha, order, profiles = load()
    wanted = {
        ZSH_OUT: render_zsh(sha, order, profiles),
        GO_OUT: render_go(sha, order, profiles),
        BASH_OUT: render_bash(sha, order, profiles),
    }

    stale = []
    for path, text in wanted.items():
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)

    rel = lambda p: p.relative_to(REPO)
    if args.check:
        if stale:
            print("stale, run agent-profiles-sync:", file=sys.stderr)
            for p in stale:
                print(f"  {rel(p)}", file=sys.stderr)
            return 1
        print(f"up to date ({sha[:12]})")
        return 0

    if stale:
        for p in stale:
            print(f"wrote {rel(p)}")
    else:
        print(f"already up to date ({sha[:12]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
