##
#: Generated by =python/agent_profiles_gen.py= from
#: =configFiles/claude-code/profiles.yaml=. DO NOT EDIT: edit the YAML and run
#: `agent-profiles-sync'. The prose explaining *why* each seat looks the way it
#: does lives in the YAML, next to the values.
#:
#: Literals rather than a parse, because every interactive shell sources this.
##
#: SHA-256 of the source, checked by =internal/profiles= in the Go module.
typeset -g claude_code_profiles_source_sha256='26f151e5630b08683628f0cf4b12171688aeec6dc2132ff8716543425e813974'


#: Iteration and display order; an associative array has none of its own.
typeset -ga claude_code_profile_order=( default work )
#: One emoji per seat, for the tty title, the status line badge and the
#: tmux pane label alike.
typeset -gA claude_code_profile_markers=(
    default  '🦋'
    work     '🏫'
)
#: The word a seat goes by where a cue has to spell it out.
typeset -gA claude_code_profile_labels=(
    default  'PERSONAL'
    work     'WORK'
)
#: The seat's identity colour as an `R;G;B' triplet, for
#: [agfi:h-claude-profile-color-hex] to hand to tmux. A seat with no entry
#: has no colour to give it.
typeset -gA claude_code_profile_colors=(
    # default  <none>
    work     '108;113;196'
)
#: The pane background each seat washes to. No entry, no tint.
typeset -gA claude_code_profile_tints=(
    # default  <none>
    work     '#f2f8f1'
)
#: The tmux style attributes added on top of the seat's colour for its pane
#: border. No entry, no border.
typeset -gA claude_code_profile_borders=(
    # default  <none>
    work     'bold'
)
#: Which tracked file under =configFiles/claude-code/themes/= a seat's
#: =themes/profile.json= points at.
typeset -gA claude_code_profile_themes=(
    default  'personal'
    work     'work'
)
#: The basename of each seat's config home, which is what a transcript's
#: path reveals and therefore how the pickers identify a seat.
typeset -gA claude_code_profile_homes=(
    default  '.claude'
    work     '.claude-work'
)
#: A seat's =CLAUDE_CONFIG_DIR=, or the empty string for the one that needs
#: none. Everything else -- config file, Keychain service, cache dir --
#: derives from this. Double-quoted, so =${HOME}= expands at source time.
typeset -gA claude_code_profiles=(
    default  ''
    work     "${HOME}/.claude-work"
)
#: The command that starts each seat, for [agfi:claude-code-session-resume].
typeset -gA claude_code_profile_launchers=(
    default  'claude-m'
    work     'claude-work'
)
