#!/usr/bin/env sh
# -*- mode: sh; sh-shell: sh; -*-
#: Stage 50: Emacs + Doom.
#:
#: Version choice: conda-forge emacs 30.2. This is NOT the laptop's 29.2, and
#: the reason is empirical, not preference:
#:
#:   - emacs-29.2-hc93ec10_0 has no binutils dependency: NO native compilation.
#:     conda-forge only gained native comp on [2024-12-05].
#:   - emacs-29.4-had6963b_1 ([2025-02-11]) has native comp, but it predates
#:     "Avoid using deprecated malloc_set_state on Linux" ([2025-03-06]) and so
#:     dies immediately on Ubuntu 24.04:
#:       emacs: symbol lookup error: undefined symbol: malloc_set_state
#:     glibc 2.39 no longer exports that compat symbol. Verified on beta.
#:   - emacs 30.2 (current recipe, build 4) carries the malloc patch AND
#:     native comp AND tree-sitter AND native JSON.
#:
#: No published 29.x build satisfies both constraints, so 30.x it is. Doom
#: 3.0.0-pre supports Emacs 30.
#:
#: Junest is deliberately NOT a fallback here: its emacs has caused problems
#: before. Fall back to an AppImage or a source build instead.

# shellcheck disable=SC1091
. "${HOME}/.night-bootstrap.env"

have micromamba || die "stage 40 (micromamba) must run first"

: "${NIGHT_EMACS_ENV:=emacs}"
: "${NIGHT_EMACS_VERSION:=30.2}"

##
#: --- emacs itself ---
emacs_prefix="${MAMBA_ROOT_PREFIX}/envs/${NIGHT_EMACS_ENV}"

emacs_ok() {
    #: "Installed" is not the same as "runs": the 29.4 build linked fine and
    #: then died on a missing glibc symbol. Always execute it.
    [ -x "${emacs_prefix}/bin/emacs" ] && \
        "${emacs_prefix}/bin/emacs" --version >/dev/null 2>&1
}

if emacs_ok ; then
    ok "emacs env already exists and runs"
else
    if [ -e "${emacs_prefix}" ] ; then
        warn "existing emacs env does not run; recreating"
        run_soft micromamba env remove --yes -n "${NIGHT_EMACS_ENV}"
    fi
    log "creating emacs env (emacs=${NIGHT_EMACS_VERSION})"
    #: sysroot_linux-64 + gcc_linux-64 are NOT pulled in by the emacs package,
    #: but native compilation is unusable without them. emacs ships its own
    #: libgccjit and invokes its own gcc driver, which was configured with
    #: --with-sysroot=$PREFIX/$HOST/sysroot; with that sysroot absent every
    #: native compile dies at link time with:
    #:   ld: cannot find crti.o / -lgcc / -lc
    #: native-comp-available-p still returns t, so this only shows up the
    #: first time something actually compiles (i.e. during `doom install`).
    run micromamba create --yes -n "${NIGHT_EMACS_ENV}" \
        -c conda-forge "emacs=${NIGHT_EMACS_VERSION}" \
        sysroot_linux-64 gcc_linux-64 \
        || die "could not create the emacs env"

    emacs_ok || die "emacs installed but will not run: $("${emacs_prefix}/bin/emacs" --version 2>&1 | head -2)"
fi

#: Expose emacs without putting the whole env on PATH (which would let conda
#: builds shadow the mise-managed tools).
#:
#: @warn Use a wrapper, NOT a symlink. conda's emacs locates its bundled
#: libgccjit toolchain relative to its own invocation path, so reaching it
#: through a symlink in ~/.local/bin makes every native compile fail with
#:   ld: cannot find crti.o / -lgcc / -lc
#: while `emacs --version` and `native-comp-available-p` both still look fine.
#: Verified on beta: symlink -> exit 255, wrapper -> exit 0.
#: `exec`ing the absolute path puts the real location in argv[0].
for b in emacs emacsclient ; do
    if [ -x "${emacs_prefix}/bin/${b}" ] ; then
        rm -f "${NIGHT_BIN}/${b}"
        cat > "${NIGHT_BIN}/${b}" <<WRAPPER
#!/bin/sh
#: Generated by setup/bootstrap/stages/50-emacs.sh
#: Must exec the real path; a symlink breaks native compilation.
exec "${emacs_prefix}/bin/${b}" "\$@"
WRAPPER
        chmod +x "${NIGHT_BIN}/${b}"
    fi
done
path_prepend "${NIGHT_BIN}"

ok "$(emacs --version 2>&1 | head -1)"

#: The whole reason we picked 29.4 over 29.2.
nc="$(emacs --batch --eval '(princ (if (native-comp-available-p) "yes" "no"))' 2>/dev/null)"
if [ "${nc}" = "yes" ] ; then
    ok "native compilation: reported available"
else
    warn "native compilation: NOT available (Doom will be noticeably slower)"
fi

#: `native-comp-available-p` only means libgccjit loaded; it says nothing
#: about whether the resulting object can be linked. Compile something for
#: real, or the first failure is 2000 packages into `doom sync`.
nc_probe="${NIGHT_LOCAL_CACHE}/nc-probe.el"
printf ';;; -*- lexical-binding: t; -*-\n(defun night-nc-probe (x) (+ x 1))\n' > "${nc_probe}"
if emacs --batch --eval "(native-compile \"${nc_probe}\")" >/dev/null 2>&1 ; then
    ok "native compilation: links successfully"
else
    warn "native compilation reports available but FAILS to link"
    warn "usually means sysroot_linux-64/gcc_linux-64 are missing from the env"
fi
rm -f "${nc_probe}"

##
#: --- Doom ---
#: Delegated to the config repo. Doom setup is not specific to this bootstrap
#: (the same config is installed by other methods), so it lives with the
#: config: ~/doom.d/bootstrap/install.sh, documented in that directory's
#: README.org. Our job here is only to provide a working `emacs' on PATH and
#: the storage layout.
#:
#: We pass DOOMLOCALDIR so the package tree (tens of thousands of small files)
#: lands on the big store rather than the quota'd home, and DOOMDIR because
#: night-loader.el reads it from the *environment* -- an unset value fails with
#: `wrong-type-argument stringp nil'.

: "${DOOMDIR:=${HOME}/doom.d}"
export DOOMDIR

if [ ! -d "${DOOMDIR}/.git" ] ; then
    log "cloning the doom config"
    run git clone https://github.com/NightMachinery/doom.d "${DOOMDIR}" \
        || die "doom.d clone failed"
fi

if [ ! -e "${HOME}/.doom.d" ] ; then
    run ln -s "${DOOMDIR}" "${HOME}/.doom.d"
    ok "linked ~/.doom.d -> ${DOOMDIR}"
fi

ensure_dir "${DOOMLOCALDIR}"

doom_installer="${DOOMDIR}/bootstrap/install.sh"
if [ -x "${doom_installer}" ] || [ -f "${doom_installer}" ] ; then
    log "running ${doom_installer}"
    if run sh "${doom_installer}" ; then
        ok "doom installed and verified"
    else
        warn "doom install reported a problem; see ${DOOMDIR}/bootstrap/README.org"
    fi
else
    warn "no ${doom_installer}; is the doom.d checkout current?"
fi
