#!/usr/bin/env zsh
ln -s "$NIGHTDIR"/bash/auto-load ~/bal
ln -s "$NIGHTDIR"/zsh/auto-load ~/zal
ln -s ~/.nvimrc ~/.config/nvim/init.vim
ln -s "$HOME/Downloads/" ~/"$music_dir"/d
# ln -s "$HOME/Downloads/Telegram Desktop/" ~/"$music_dir"/td