#!/usr/bin/env zsh
tic -x -o ~/.terminfo "$NIGHTDIR"/setup/terminfo-24bit.src

# git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

curl https://cht.sh/:cht.sh > ~/bin/cht.sh
chmod +x ~/bin/cht.sh
###
conda install -c eumetsat expect
conda install -c plotly plotly-orca # also can be installed via npm
conda install -c numba icc_rt
##
pig https://github.com/NightMachinary/BrishGarden.git
pig git@github.com:NightMachinary/brish.git
pi git+https://github.com/n8henrie/pycookiecheat.git@dev
###
cpanm App::ansifold
##
nimble install https://github.com/NightMachinary/htmlmetadata
##
brew tap v2ray/v2ray
brew install v2ray-core
brew tap lutzifer/homebrew-tap
brew install keyboardSwitcher
brew tap trojan-gfw/homebrew-trojan
brew install trojan
brew install --head googler
brew install --head tdlib
##
# https://superuser.com/questions/545889/how-can-i-install-gnu-parallel-alongside-moreutils
brew install --force moreutils
brew unlink moreutils
brew install --force parallel
brew link --overwrite moreutils
brew unlink parallel
brew link --overwrite parallel
echo 'will cite' | command parallel --citation 1> /dev/null 2> /dev/null
##
luarocks install penlight # require 'pl.pretty'.dump(table)
luarocks install luaposix
##
