#!/usr/bin/env sh
# -*- mode: sh; sh-shell: sh; -*-
#: Stage 00: storage layout.
#: Creates the three tiers and writes the env contract that later stages,
#: and the interactive shell, both read.

ensure_dir "${NIGHT_BIN}"
ensure_dir "${NIGHT_LOCAL_CACHE}"
ensure_dir "${HOME}/code"
ensure_dir "${HOME}/tmp"

#: The big store may be on a filesystem we cannot write (misconfigured
#: profile, unmounted NFS). Fail loudly here rather than halfway through a
#: 2 GB conda install.
if ! mkdir -p "${NIGHT_BIG_STORE}" 2>/dev/null ; then
    die "cannot create NIGHT_BIG_STORE=${NIGHT_BIG_STORE} (override it in the environment)"
fi
if ! ( : > "${NIGHT_BIG_STORE}/.write-test" ) 2>/dev/null ; then
    die "NIGHT_BIG_STORE=${NIGHT_BIG_STORE} is not writable"
fi
rm -f "${NIGHT_BIG_STORE}/.write-test"

ensure_dir "${NIGHT_BIG_STORE}/envs"
ensure_dir "${NIGHT_BIG_STORE}/cache"

##
#: --- privacy on a shared login node ---
#: Only when other people can log in here; on a single-user box these would be
#: needless friction (e.g. you could no longer hand a collaborator a path).
#: These directories default to 755, which would expose models, datasets,
#: fitted lenses and logs to every other user of the cluster. The parent
#: /mounts/work is 1777 and not ours to change, but that does not matter: a
#: child directory's own mode gates access to its contents, and the parent's
#: sticky bit (the `t') is what stops others deleting our directory despite
#: the parent being world-writable.
if [ "${NIGHT_MULTIUSER}" = y ] ; then
    for d in "${NIGHT_BIG_STORE}" "${NIGHT_LOCAL_CACHE}" "${HOME}/code" ; do
        [ -d "${d}" ] && run_soft chmod 700 "${d}"
    done
fi

#: Existing top-level entries in $HOME were created under umask 022 and are
#: world-readable; $HOME is only 711 (traversable), so anyone who guesses a
#: standard name -- .privateShell, .zcompdump, .emacs.d -- can read it.
#: We deliberately do NOT chmod $HOME itself; see the umask note in the env
#: contract below.
if [ -n "${NIGHT_BOOTSTRAP_HARDEN_HOME:-}" ] ; then
    find "${HOME}" -maxdepth 1 -mindepth 1 \! -type l -exec chmod go-rwx {} + 2>/dev/null
    ok "removed group/other access from top-level \$HOME entries"
fi

##
#: --- site marker ---
#: Records which profile this home belongs to, so later runs (and other
#: programs, e.g. night/cis-p in doom.d/config.el) can *read* the answer
#: instead of inferring it. Named generically, and holding the profile name,
#: because the site is a variable here -- CIS is one value, not the concept.
#: Where $HOME is shared, one file covers every host in the cluster.
if [ ! -e "${night_site_file}" ] && [ "${NIGHT_PROFILE}" != "default" ] ; then
    {
        printf '%s\n' "${NIGHT_PROFILE}"
        cat <<'MARK'

# Written by setup/bootstrap-sudoless/stages/00-dirs.sh.
# The first non-comment line is the profile name.
#
# An explicit declaration on purpose: every inferrable signal was wrong in some
# way. A mount point only proves the share is mounted; a $HOME path prefix is a
# naming convention, not an identity; the DNS search domain tracks network
# connectivity (the laptop matched it over VPN); hostnames need per-machine
# upkeep and collide.

"Begin at the beginning," the King said, very gravely,
"and go on till you come to the end: then stop."
  -- Alice's Adventures in Wonderland
MARK
    } > "${night_site_file}"
    chmod 600 "${night_site_file}"
    ok "wrote ${night_site_file} (${NIGHT_PROFILE})"
fi

##
#: The env contract. Sourced by ~/.privateShell (stage 10) so an interactive
#: shell agrees with the bootstrap about where things live.
env_file="${HOME}/.night-bootstrap.env"

cat > "${env_file}" <<EOF
# -*- mode: sh; -*-
#: Generated by setup/bootstrap-sudoless/stages/00-dirs.sh
#: Storage contract for this host. Edit NIGHT_BIG_STORE here (or in
#: setup/bootstrap-sudoless/profiles/) to relocate the heavy trees.
#:
#: ############################################################################
#: @warn THIS FILE IS SHARED BY EVERY HOST.
#:
#: It lives in \$HOME, and on the CIS cluster \$HOME is one NFS mount shared by
#: ~12 machines. So this is *one file* that beta, rho*, zeta* and epsilon* all
#: source. Consequences:
#:
#:   - Never write a host-specific *value* here. Write an expression that
#:     *derives* the value per host, e.g. EMACS_SOCKET_NAME below uses \\\$HOST.
#:     A literal hostname would be silently wrong on the other eleven.
#:   - Regenerating it on one host regenerates it for all of them. Stages
#:     append to it, so a rerun of stage 00 discards those appends.
#:   - It is chmod 600: it carries REDISCLI_AUTH. Keep it that way.
#:   - Values that must differ per host belong under \$NIGHT_LOCAL_CACHE
#:     (per-host local disk), not in here.
#: ############################################################################

export NIGHT_PROFILE='${NIGHT_PROFILE}'
export NIGHT_BIN='${NIGHT_BIN}'
export NIGHT_BIG_STORE='${NIGHT_BIG_STORE}'
export NIGHT_LOCAL_CACHE='${NIGHT_LOCAL_CACHE}'

#: Package managers: keep cache and envs on the SAME filesystem, or conda /
#: pixi hardlink dedup breaks and every env stores real copies.
export MAMBA_ROOT_PREFIX="\${NIGHT_BIG_STORE}/mamba"
export CONDA_ENVS_DIRS="\${NIGHT_BIG_STORE}/mamba/envs"
export CONDA_PKGS_DIRS="\${NIGHT_BIG_STORE}/mamba/pkgs"
export PIXI_HOME="\${NIGHT_BIG_STORE}/pixi"
export UV_CACHE_DIR="\${NIGHT_LOCAL_CACHE}/uv"

#: Doom's whole .local tree (straight repos, builds, eln cache) is tens of
#: thousands of small files: keep it off the quota'd home.
export DOOMLOCALDIR="\${NIGHT_BIG_STORE}/doom-local/"

#: mise manages the static CLI binaries and language runtimes.
export MISE_DATA_DIR="\${NIGHT_BIG_STORE}/mise"
export MISE_CACHE_DIR="\${NIGHT_LOCAL_CACHE}/mise"

case ":\${PATH}:" in
    *":\${NIGHT_BIN}:"*) : ;;
    *) export PATH="\${NIGHT_BIN}:\${PATH}" ;;
esac

#: --- variables smuggled through ssh ---
#: sshd forwards only what AcceptEnv permits (commonly, and here, "LANG LC_*"),
#: so the client sends LC_<NAME> and we restore <NAME>. The implementation is
#: [agfi:env-load-smuggled-lc-vars] in zshlang/basic/ssh.zsh -- it is ordinary
#: shell functionality, not bootstrap-specific, so it lives with the rest of
#: the shell library rather than being duplicated here.
#:
#: Guarded because this file is also sourced by POSIX sh (the bootstrap
#: stages), where zshlang is not loaded; those contexts do not need it.
if command -v env-load-smuggled-lc-vars >/dev/null 2>&1 ; then
    env-load-smuggled-lc-vars
fi

#: These are multi-user login nodes, and the default umask 0022 creates every
#: file world-readable. 077 makes new files 600 and new dirs 700.
#: @note \$HOME itself stays at the cluster's 711 convention (103 of 108 homes
#: use it) rather than 700: sshd reads ~/.ssh/authorized_keys, and on an NFS
#: home with root_squash a 700 home risks breaking key auth. 711 plus private
#: contents gives the same privacy without the lockout risk.
umask 077

#: redis listens on 127.0.0.1, which keeps out other *hosts* but NOT other
#: *users* of this machine -- and these are shared login nodes. So redis runs
#: with requirepass. redis-cli reads REDISCLI_AUTH automatically, so
#: [agfi:redis-cli-wrapper] and friends need no change.
#: /proc/PID/environ is owner-readable only, so exporting it does not leak it.
if [ -r "\${HOME}/.redis-auth" ] ; then
    REDISCLI_AUTH="\$(cat "\${HOME}/.redis-auth")"
    export REDISCLI_AUTH
fi
EOF

chmod 600 "${env_file}"
ok "wrote ${env_file} (chmod 600; shared by every host)"
dim "big store:   ${NIGHT_BIG_STORE}"
dim "local cache: ${NIGHT_LOCAL_CACHE}"
