#!/usr/bin/env sh
# -*- mode: sh; sh-shell: sh; -*-
#: Stage 00: storage layout.
#: Creates the three tiers and writes the env contract that later stages,
#: and the interactive shell, both read.

ensure_dir "${NIGHT_BIN}"
ensure_dir "${NIGHT_LOCAL_CACHE}"
ensure_dir "${HOME}/code"
ensure_dir "${HOME}/tmp"

#: The big store may be on a filesystem we cannot write (misconfigured
#: profile, unmounted NFS). Fail loudly here rather than halfway through a
#: 2 GB conda install.
if ! mkdir -p "${NIGHT_BIG_STORE}" 2>/dev/null ; then
    die "cannot create NIGHT_BIG_STORE=${NIGHT_BIG_STORE} (override it in the environment)"
fi
if ! ( : > "${NIGHT_BIG_STORE}/.write-test" ) 2>/dev/null ; then
    die "NIGHT_BIG_STORE=${NIGHT_BIG_STORE} is not writable"
fi
rm -f "${NIGHT_BIG_STORE}/.write-test"

ensure_dir "${NIGHT_BIG_STORE}/envs"
ensure_dir "${NIGHT_BIG_STORE}/cache"

##
#: The env contract. Sourced by ~/.privateShell (stage 10) so an interactive
#: shell agrees with the bootstrap about where things live.
env_file="${HOME}/.night-bootstrap.env"

cat > "${env_file}" <<EOF
# -*- mode: sh; -*-
#: Generated by setup/bootstrap-sudoless/stages/00-dirs.sh
#: Storage contract for this host. Edit NIGHT_BIG_STORE here (or in
#: setup/bootstrap-sudoless/profiles/) to relocate the heavy trees.

export NIGHT_PROFILE='${NIGHT_PROFILE}'
export NIGHT_BIN='${NIGHT_BIN}'
export NIGHT_BIG_STORE='${NIGHT_BIG_STORE}'
export NIGHT_LOCAL_CACHE='${NIGHT_LOCAL_CACHE}'

#: Package managers: keep cache and envs on the SAME filesystem, or conda /
#: pixi hardlink dedup breaks and every env stores real copies.
export MAMBA_ROOT_PREFIX="\${NIGHT_BIG_STORE}/mamba"
export CONDA_ENVS_DIRS="\${NIGHT_BIG_STORE}/mamba/envs"
export CONDA_PKGS_DIRS="\${NIGHT_BIG_STORE}/mamba/pkgs"
export PIXI_HOME="\${NIGHT_BIG_STORE}/pixi"
export UV_CACHE_DIR="\${NIGHT_LOCAL_CACHE}/uv"

#: Doom's whole .local tree (straight repos, builds, eln cache) is tens of
#: thousands of small files: keep it off the quota'd home.
export DOOMLOCALDIR="\${NIGHT_BIG_STORE}/doom-local/"

#: mise manages the static CLI binaries and language runtimes.
export MISE_DATA_DIR="\${NIGHT_BIG_STORE}/mise"
export MISE_CACHE_DIR="\${NIGHT_LOCAL_CACHE}/mise"

case ":\${PATH}:" in
    *":\${NIGHT_BIN}:"*) : ;;
    *) export PATH="\${NIGHT_BIN}:\${PATH}" ;;
esac
EOF

ok "wrote ${env_file}"
dim "big store:   ${NIGHT_BIG_STORE}"
dim "local cache: ${NIGHT_LOCAL_CACHE}"
