#!/usr/bin/env sh
# -*- mode: sh; sh-shell: sh; -*-
#: Stage 00: storage layout.
#: Creates the three tiers and writes the env contract that later stages,
#: and the interactive shell, both read.

ensure_dir "${NIGHT_BIN}"
ensure_dir "${NIGHT_LOCAL_CACHE}"
ensure_dir "${HOME}/code"
ensure_dir "${HOME}/tmp"

#: The big store may be on a filesystem we cannot write (misconfigured
#: profile, unmounted NFS). Fail loudly here rather than halfway through a
#: 2 GB conda install.
if ! mkdir -p "${NIGHT_BIG_STORE}" 2>/dev/null ; then
    die "cannot create NIGHT_BIG_STORE=${NIGHT_BIG_STORE} (override it in the environment)"
fi
if ! ( : > "${NIGHT_BIG_STORE}/.write-test" ) 2>/dev/null ; then
    die "NIGHT_BIG_STORE=${NIGHT_BIG_STORE} is not writable"
fi
rm -f "${NIGHT_BIG_STORE}/.write-test"

ensure_dir "${NIGHT_BIG_STORE}/envs"
ensure_dir "${NIGHT_BIG_STORE}/cache"

##
#: The env contract. Sourced by ~/.privateShell (stage 10) so an interactive
#: shell agrees with the bootstrap about where things live.
env_file="${HOME}/.night-bootstrap.env"

cat > "${env_file}" <<EOF
# -*- mode: sh; -*-
#: Generated by setup/bootstrap-sudoless/stages/00-dirs.sh
#: Storage contract for this host. Edit NIGHT_BIG_STORE here (or in
#: setup/bootstrap-sudoless/profiles/) to relocate the heavy trees.
#:
#: ############################################################################
#: @warn THIS FILE IS SHARED BY EVERY HOST.
#:
#: It lives in \$HOME, and on the CIS cluster \$HOME is one NFS mount shared by
#: ~12 machines. So this is *one file* that beta, rho*, zeta* and epsilon* all
#: source. Consequences:
#:
#:   - Never write a host-specific *value* here. Write an expression that
#:     *derives* the value per host, e.g. EMACS_SOCKET_NAME below uses \\\$HOST.
#:     A literal hostname would be silently wrong on the other eleven.
#:   - Regenerating it on one host regenerates it for all of them. Stages
#:     append to it, so a rerun of stage 00 discards those appends.
#:   - It is chmod 600: it carries REDISCLI_AUTH. Keep it that way.
#:   - Values that must differ per host belong under \$NIGHT_LOCAL_CACHE
#:     (per-host local disk), not in here.
#: ############################################################################

export NIGHT_PROFILE='${NIGHT_PROFILE}'
export NIGHT_BIN='${NIGHT_BIN}'
export NIGHT_BIG_STORE='${NIGHT_BIG_STORE}'
export NIGHT_LOCAL_CACHE='${NIGHT_LOCAL_CACHE}'

#: Package managers: keep cache and envs on the SAME filesystem, or conda /
#: pixi hardlink dedup breaks and every env stores real copies.
export MAMBA_ROOT_PREFIX="\${NIGHT_BIG_STORE}/mamba"
export CONDA_ENVS_DIRS="\${NIGHT_BIG_STORE}/mamba/envs"
export CONDA_PKGS_DIRS="\${NIGHT_BIG_STORE}/mamba/pkgs"
export PIXI_HOME="\${NIGHT_BIG_STORE}/pixi"
export UV_CACHE_DIR="\${NIGHT_LOCAL_CACHE}/uv"

#: Doom's whole .local tree (straight repos, builds, eln cache) is tens of
#: thousands of small files: keep it off the quota'd home.
export DOOMLOCALDIR="\${NIGHT_BIG_STORE}/doom-local/"

#: mise manages the static CLI binaries and language runtimes.
export MISE_DATA_DIR="\${NIGHT_BIG_STORE}/mise"
export MISE_CACHE_DIR="\${NIGHT_LOCAL_CACHE}/mise"

case ":\${PATH}:" in
    *":\${NIGHT_BIN}:"*) : ;;
    *) export PATH="\${NIGHT_BIN}:\${PATH}" ;;
esac

#: redis listens on 127.0.0.1, which keeps out other *hosts* but NOT other
#: *users* of this machine -- and these are shared login nodes. So redis runs
#: with requirepass. redis-cli reads REDISCLI_AUTH automatically, so
#: [agfi:redis-cli-wrapper] and friends need no change.
#: /proc/PID/environ is owner-readable only, so exporting it does not leak it.
if [ -r "\${HOME}/.redis-auth" ] ; then
    REDISCLI_AUTH="\$(cat "\${HOME}/.redis-auth")"
    export REDISCLI_AUTH
fi
EOF

chmod 600 "${env_file}"
ok "wrote ${env_file} (chmod 600; shared by every host)"
dim "big store:   ${NIGHT_BIG_STORE}"
dim "local cache: ${NIGHT_LOCAL_CACHE}"
