#!/usr/bin/env sh
# -*- mode: sh; sh-shell: sh; -*-
#: Stage 50: Emacs + Doom.
#:
#: Version choice: conda-forge emacs 30.2. This is NOT the laptop's 29.2, and
#: the reason is empirical, not preference:
#:
#:   - emacs-29.2-hc93ec10_0 has no binutils dependency: NO native compilation.
#:     conda-forge only gained native comp on [2024-12-05].
#:   - emacs-29.4-had6963b_1 ([2025-02-11]) has native comp, but it predates
#:     "Avoid using deprecated malloc_set_state on Linux" ([2025-03-06]) and so
#:     dies immediately on Ubuntu 24.04:
#:       emacs: symbol lookup error: undefined symbol: malloc_set_state
#:     glibc 2.39 no longer exports that compat symbol. Verified on beta.
#:   - emacs 30.2 (current recipe, build 4) carries the malloc patch AND
#:     native comp AND tree-sitter AND native JSON.
#:
#: No published 29.x build satisfies both constraints, so 30.x it is. Doom
#: 3.0.0-pre supports Emacs 30.
#:
#: Junest is deliberately NOT a fallback here: its emacs has caused problems
#: before. Fall back to an AppImage or a source build instead.

# shellcheck disable=SC1091
. "${HOME}/.night-bootstrap.env"

have micromamba || die "stage 40 (micromamba) must run first"

: "${NIGHT_EMACS_ENV:=emacs}"
: "${NIGHT_EMACS_VERSION:=30.2}"

##
#: --- emacs itself ---
emacs_prefix="${MAMBA_ROOT_PREFIX}/envs/${NIGHT_EMACS_ENV}"

emacs_ok() {
    #: "Installed" is not the same as "runs": the 29.4 build linked fine and
    #: then died on a missing glibc symbol. Always execute it.
    [ -x "${emacs_prefix}/bin/emacs" ] && \
        "${emacs_prefix}/bin/emacs" --version >/dev/null 2>&1
}

if emacs_ok ; then
    ok "emacs env already exists and runs"
else
    if [ -e "${emacs_prefix}" ] ; then
        warn "existing emacs env does not run; recreating"
        run_soft micromamba env remove --yes -n "${NIGHT_EMACS_ENV}"
    fi
    log "creating emacs env (emacs=${NIGHT_EMACS_VERSION})"
    #: sysroot_linux-64 + gcc_linux-64 are NOT pulled in by the emacs package,
    #: but native compilation is unusable without them. emacs ships its own
    #: libgccjit and invokes its own gcc driver, which was configured with
    #: --with-sysroot=$PREFIX/$HOST/sysroot; with that sysroot absent every
    #: native compile dies at link time with:
    #:   ld: cannot find crti.o / -lgcc / -lc
    #: native-comp-available-p still returns t, so this only shows up the
    #: first time something actually compiles (i.e. during `doom install`).
    run micromamba create --yes -n "${NIGHT_EMACS_ENV}" \
        -c conda-forge "emacs=${NIGHT_EMACS_VERSION}" \
        sysroot_linux-64 gcc_linux-64 \
        || die "could not create the emacs env"

    emacs_ok || die "emacs installed but will not run: $("${emacs_prefix}/bin/emacs" --version 2>&1 | head -2)"
fi

#: Expose emacs without putting the whole env on PATH (which would let conda
#: builds shadow the mise-managed tools).
#:
#: @warn Use a wrapper, NOT a symlink. conda's emacs locates its bundled
#: libgccjit toolchain relative to its own invocation path, so reaching it
#: through a symlink in ~/.local/bin makes every native compile fail with
#:   ld: cannot find crti.o / -lgcc / -lc
#: while `emacs --version` and `native-comp-available-p` both still look fine.
#: Verified on beta: symlink -> exit 255, wrapper -> exit 0.
#: `exec`ing the absolute path puts the real location in argv[0].
for b in emacs emacsclient ; do
    if [ -x "${emacs_prefix}/bin/${b}" ] ; then
        rm -f "${NIGHT_BIN}/${b}"
        cat > "${NIGHT_BIN}/${b}" <<WRAPPER
#!/bin/sh
#: Generated by setup/bootstrap-sudoless/stages/50-emacs.sh
#: Must exec the real path; a symlink breaks native compilation.
exec "${emacs_prefix}/bin/${b}" "\$@"
WRAPPER
        chmod +x "${NIGHT_BIN}/${b}"
    fi
done
path_prepend "${NIGHT_BIN}"

ok "$(emacs --version 2>&1 | head -1)"

#: The whole reason we picked 29.4 over 29.2.
nc="$(emacs --batch --eval '(princ (if (native-comp-available-p) "yes" "no"))' 2>/dev/null)"
if [ "${nc}" = "yes" ] ; then
    ok "native compilation: reported available"
else
    warn "native compilation: NOT available (Doom will be noticeably slower)"
fi

#: `native-comp-available-p` only means libgccjit loaded; it says nothing
#: about whether the resulting object can be linked. Compile something for
#: real, or the first failure is 2000 packages into `doom sync`.
nc_probe="${NIGHT_LOCAL_CACHE}/nc-probe.el"
printf ';;; -*- lexical-binding: t; -*-\n(defun night-nc-probe (x) (+ x 1))\n' > "${nc_probe}"
if emacs --batch --eval "(native-compile \"${nc_probe}\")" >/dev/null 2>&1 ; then
    ok "native compilation: links successfully"
else
    warn "native compilation reports available but FAILS to link"
    warn "usually means sysroot_linux-64/gcc_linux-64 are missing from the env"
fi
rm -f "${nc_probe}"

##
#: --- Doom ---
#: DOOMLOCALDIR (set in the env contract) moves straight/, builds and the eln
#: cache onto the big store: tens of thousands of small files that must not
#: sit inside the 48 GB home quota.
ensure_dir "${DOOMLOCALDIR}"

#: Pin doom to the same commit as the laptop. Doom 3.x master moves fast and
#: the doom.d config carries version-specific workarounds -- e.g. config.el
#: does `(require 'doom-themes-ext-org)` "@workaround for upstream bugs", but
#: a doom master from [2026-08] no longer installs doom-themes for `:ui doom`,
#: so a fresh master clone boots with:
#:   Error caused by user's config: (file-missing ... doom-themes-ext-org)
#: Bump deliberately, not by accident of clone date.
: "${NIGHT_DOOM_REF:=fb9b359db}"

if [ -d "${HOME}/.emacs.d/.git" ] ; then
    ok "doom already cloned"
else
    #: ~/.emacs is backed up in stage 10; it would shadow doom's init.
    log "cloning doomemacs"
    run git clone https://github.com/doomemacs/doomemacs "${HOME}/.emacs.d" \
        || die "doom clone failed"
fi

current_ref="$(git -C "${HOME}/.emacs.d" rev-parse --short HEAD 2>/dev/null || echo none)"
case "${NIGHT_DOOM_REF}" in
    "${current_ref}"*) ok "doom pinned at ${current_ref}" ;;
    *)
        log "pinning doom to ${NIGHT_DOOM_REF} (was ${current_ref})"
        #: An earlier --depth 1 clone cannot reach an older commit; unshallow
        #: before fetching or the checkout fails with "reference is not a tree".
        if [ -f "${HOME}/.emacs.d/.git/shallow" ] ; then
            run_soft git -C "${HOME}/.emacs.d" fetch --quiet --unshallow origin
        fi
        run_soft git -C "${HOME}/.emacs.d" fetch --quiet origin
        run git -C "${HOME}/.emacs.d" checkout --quiet "${NIGHT_DOOM_REF}" \
            || die "could not pin doom to ${NIGHT_DOOM_REF}"
        ;;
esac

#: @warn The package tree is only valid for the doom revision that built it.
#: Changing NIGHT_DOOM_REF after a sync leaves straight/ pinned to the other
#: revision's package set; `doom sync` then tries to move already-built repos
#: and stops on an interactive "How to proceed? (1,2,3,4,5)" conflict prompt.
#: With stdin closed that aborts with `end-of-file` *before* the profile init
#: is written, and the next daemon start dies with
#:   Symbol's value as variable is void: doom--profile-default
#: A fresh tree cannot conflict, so rebuild whenever the pin moves.
doom_ref_stamp="${DOOMLOCALDIR}/.night-doom-ref"
doom_ref_now="$(git -C "${HOME}/.emacs.d" rev-parse HEAD 2>/dev/null || echo unknown)"
if [ -f "${doom_ref_stamp}" ] && [ "$(cat "${doom_ref_stamp}")" != "${doom_ref_now}" ] ; then
    warn "doom revision changed since the last sync; rebuilding DOOMLOCALDIR"
    warn "  was $(cat "${doom_ref_stamp}")"
    warn "  now ${doom_ref_now}"
    run_soft mv "${DOOMLOCALDIR%/}" "${DOOMLOCALDIR%/}.stale-$$"
    ensure_dir "${DOOMLOCALDIR}"
fi


if [ -d "${HOME}/doom.d/.git" ] ; then
    ok "doom.d config already cloned"
else
    log "cloning the doom.d config"
    run git clone https://github.com/NightMachinery/doom.d "${HOME}/doom.d" \
        || die "doom.d clone failed"
fi

#: Only the submodules that are actually checked out on the laptop and
#: referenced by the config. `radian` and `emacswiki` are intentionally
#: skipped -- neither is initialized locally, and emacswiki's .gitmodules URL
#: uses the git:// protocol, which GitHub disabled in 2022.
( cd "${HOME}/doom.d" && \
  run_soft git submodule update --init --depth 1 \
      gitmodules/fzf.el \
      gitmodules/osx-clipboard-mode \
      gitmodules/pdf-continuous-scroll-mode.el )

if [ ! -e "${HOME}/.doom.d" ] ; then
    run ln -s "${HOME}/doom.d" "${HOME}/.doom.d"
    ok "linked ~/.doom.d -> ~/doom.d"
fi

#: night-loader.el loads ~/.private-config.el with NOERROR, so a missing
#: secrets file is fine; we deliberately do NOT copy secrets to a shared
#: university host.

##
log "doom sync (slow on first run: it builds every package)"
export DOOMLOCALDIR
#: Doom 3.0.0-pre's `install` accepts only:
#:   [--aot] [--[no-]config] [--[no-]env] [--[no-]install] [--[no-]hooks]
#: (no --force, no --fonts).
#:   --no-config: ~/.doom.d is already cloned.
#:   --no-env:    a shared NFS home means one host's env dump would be
#:                inherited by the other eleven.
#:   --no-hooks:  it otherwise prompts "install git hooks anyway? (y or n)"
#:                on stdin and dies with end-of-file in a non-interactive run.
if [ ! -e "${DOOMLOCALDIR}/straight" ] ; then
    run_soft "${HOME}/.emacs.d/bin/doom" install --no-env --no-config --no-hooks
fi
#: Belt and braces: nothing in this stage may ever wait on stdin.
run_soft "${HOME}/.emacs.d/bin/doom" sync < /dev/null

#: Record the revision this tree was built against, for the check above.
printf '%s' "${doom_ref_now}" > "${doom_ref_stamp}"

##
#: @warn A batch load of early-init.el is NOT sufficient: it succeeds even when
#: the generated profile init is missing, because the interactive path is what
#: loads it. Start a real daemon -- that is the failure mode users actually hit
#: (`emc-gateway` / `emacsclient -t`).
if [ -f "${DOOMLOCALDIR}/etc/@/init.${NIGHT_EMACS_VERSION%.*}.2.el" ] ||
   find "${DOOMLOCALDIR}/etc" -name 'init*.el' 2>/dev/null | grep -q . ; then
    ok "generated profile init present"
else
    err "generated profile init MISSING -- doom sync did not complete"
fi

if timeout -k 5 300 emacs --daemon=night-verify >/dev/null 2>&1 &&
   emacsclient -s night-verify --eval '(+ 1 1)' >/dev/null 2>&1 ; then
    ok "doom daemon starts and answers"
    emacsclient -s night-verify --eval '(kill-emacs)' >/dev/null 2>&1 || true
else
    warn "doom daemon did not start; run: emacs --daemon --debug-init"
    emacsclient -s night-verify --eval '(kill-emacs)' >/dev/null 2>&1 || true
fi
