#!/usr/bin/env sh
# -*- mode: sh; sh-shell: sh; -*-
#: Stage 70: per-boot services, via systemd *user* units.
#:
#: Why systemd --user rather than cron:
#:
#:   - It needs no root, and `systemctl --user' is running on these hosts.
#:   - The unit files live in ~/.config/systemd/user/, which is on the shared
#:     NFS home -- so writing one unit configures every host at once, and
#:     `systemctl --user enable' puts its symlink in the shared
#:     default.target.wants/ too. Crontabs, by contrast, live in
#:     /var/spool/cron/crontabs/ on each host's *local* disk, so they would
#:     have to be copied to all ~12 machines by hand and kept in sync forever.
#:   - You also get restart-on-failure, ordering, and `journalctl --user'.
#:
#: Starting at boot (rather than at first login) additionally needs lingering,
#: which is per-host state under /var/lib/systemd/linger/ on local disk. It
#: also keeps $XDG_RUNTIME_DIR alive across logout, which matters because the
#: emacs socket lives there (see night/emacs-socket-dir in doom.d/config.el).

# shellcheck disable=SC1091
. "${HOME}/.night-bootstrap.env"

have systemctl || {
    warn "no systemctl; skipping services (add an @reboot crontab entry instead)"
    return 0 2>/dev/null || exit 0
}

if ! systemctl --user is-system-running >/dev/null 2>&1 ; then
    warn "systemd --user is not running here; skipping"
    return 0 2>/dev/null || exit 0
fi

##
#: --- lingering: start at boot, and keep XDG_RUNTIME_DIR alive ---
if [ -e "/var/lib/systemd/linger/$(id -un)" ] ; then
    ok "lingering already enabled"
else
    if run_soft loginctl enable-linger "$(id -un)" &&
       [ -e "/var/lib/systemd/linger/$(id -un)" ] ; then
        ok "lingering enabled (services now start at boot)"
    else
        warn "could not enable lingering; services will start at first login only"
        warn "and \$XDG_RUNTIME_DIR will be removed at logout"
    fi
fi

##
#: --- the startup script ---
#: Kept as a normal zsh script the user can edit, rather than encoding service
#: definitions in units: it is the natural place to add per-boot odds and ends.
startup="${HOME}/.startup..private..zsh"
if [ -e "${startup}" ] ; then
    ok "startup script already exists: ${startup}"
else
    cat > "${startup}" <<'STARTUP'
#!/usr/bin/env zsh
#: Per-boot startup for this host, run by the `night-startup' systemd user unit.
#:
#: @warn This file is on the SHARED NFS home, so it runs on every CIS host.
#: Keep it host-agnostic: start per-host *instances*, never write host-specific
#: paths. Per-host state belongs under $NIGHT_LOCAL_CACHE.
#:
#: Everything here must be idempotent; the unit can be restarted by hand.

emulate -L zsh
setopt err_return no_unset pipe_fail

source "${HOME}/.night-bootstrap.env" || return 1
path=( "${NIGHT_BIN}" "${MISE_DATA_DIR}/shims" $path "${NIGHT_TOOLS_BIN}" )

##
#: redis. Loopback-only *and* password-protected: 127.0.0.1 keeps out other
#: hosts but not the other users of this shared login node.
function night-startup-redis {
    (( ${+commands[redis-server]} )) || return 0
    redis-cli ping &>/dev/null && return 0   #: already up

    mkdir -p "${NIGHT_LOCAL_CACHE}/redis"
    chmod 700 "${NIGHT_LOCAL_CACHE}/redis"
    redis-server \
        --daemonize yes \
        --bind 127.0.0.1 --port 6379 \
        --requirepass "$(<"${HOME}/.redis-auth")" \
        --unixsocket "${NIGHT_LOCAL_CACHE}/redis/redis.sock" --unixsocketperm 700 \
        --dir "${NIGHT_LOCAL_CACHE}/redis" --save '' --appendonly no \
        --logfile "${NIGHT_LOCAL_CACHE}/redis/redis.log"
}

#: emacs daemon. Its socket is on host-local storage, so one per host.
function night-startup-emacs {
    (( ${+commands[emacs]} )) || return 0
    emacsclient --eval t &>/dev/null && return 0   #: already serving
    emacs --daemon
}

night-startup-redis || print -ru2 -- "night-startup: redis failed"
night-startup-emacs || print -ru2 -- "night-startup: emacs failed"
print -r -- "night-startup: done on ${HOST:-$(hostname -s)}"
STARTUP
    chmod 700 "${startup}"
    ok "wrote ${startup}"
fi

##
#: --- the unit ---
unit_dir="${HOME}/.config/systemd/user"
ensure_dir "${unit_dir}"
cat > "${unit_dir}/night-startup.service" <<'UNIT'
[Unit]
# Generated by setup/bootstrap-sudoless/stages/70-services.sh
# This file is on the shared NFS home, so every host sees it; enabling it once
# enables it everywhere. Starting at boot additionally requires lingering.
Description=NightMachinary per-boot startup (redis, emacs daemon)
After=default.target

[Service]
Type=oneshot
# The daemons background themselves; without RemainAfterExit the unit would
# report inactive immediately after a successful start.
RemainAfterExit=yes
ExecStart=%h/.startup..private..zsh
TimeoutStartSec=900

[Install]
WantedBy=default.target
UNIT

run_soft systemctl --user daemon-reload
run_soft systemctl --user enable night-startup.service
run_soft systemctl --user start night-startup.service

if systemctl --user is-active night-startup.service >/dev/null 2>&1 ; then
    ok "night-startup.service active"
else
    warn "night-startup.service not active; see: journalctl --user -u night-startup"
fi

##
log "service check"
for c in redis-cli emacsclient ; do
    have "${c}" || continue
    case "${c}" in
        redis-cli)   printf '     %-12s %s\n' redis "$(redis-cli ping 2>&1 | head -1)" >&2 ;;
        emacsclient) printf '     %-12s %s\n' emacs "$(emacsclient --eval t 2>&1 | head -1)" >&2 ;;
    esac
done
