package main

import (
	"strings"
	"testing"
)

func TestShiftHeadings(t *testing.T) {
	cases := []struct {
		name, in, want string
		min            int
	}{
		{
			name: "normalizes shallowest to min, keeping relative depth",
			min:  3,
			in:   "# a\n\ntext\n\n## b\n\n#### c",
			want: "### a\n\ntext\n\n#### b\n\n###### c",
		},
		{
			name: "leaves fenced code alone",
			min:  3,
			in:   "# a\n\n```sh\n# not a heading\n## also not\n```\n\n## b",
			want: "### a\n\n```sh\n# not a heading\n## also not\n```\n\n#### b",
		},
		{
			name: "tilde fences count too",
			min:  2,
			in:   "# a\n\n~~~\n# nope\n~~~",
			want: "## a\n\n~~~\n# nope\n~~~",
		},
		{
			name: "a longer fence does not close a shorter one",
			min:  2,
			in:   "# a\n\n````\n```\n# nope\n````\n\n# b",
			want: "## a\n\n````\n```\n# nope\n````\n\n## b",
		},
		{
			name: "no headings, no change",
			min:  3,
			// `#no-space` is not an ATX heading, and neither is `####### x`.
			in:   "just text\n#nospace\n####### seven",
			want: "just text\n#nospace\n####### seven",
		},
		{
			name: "clamps at six",
			min:  6,
			in:   "# a\n\n## b",
			want: "###### a\n\n###### b",
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := shiftHeadings(c.in, c.min); got != c.want {
				t.Errorf("shiftHeadings(%q, %d)\n got: %q\nwant: %q", c.in, c.min, got, c.want)
			}
		})
	}
}

// The output must stay interchangeable with diff -U3; it was off by one on
// hunk merging until a fixture like this pinned it down.
func TestUnifiedDiff(t *testing.T) {
	a := strings.Split("l1\nl2\nl3\nl4\nl5\nl6\nl7\nl8\nl9\nl10\nl11\nl12", "\n")
	b := append([]string{}, a...)
	b[1] = "l2 changed"
	b[10] = "l11 changed"

	got, ok := unifiedDiff(a, b, 3)
	if !ok {
		t.Fatal("unifiedDiff declined inputs it should handle")
	}

	want := []string{
		"@@ -1,5 +1,5 @@",
		" l1",
		"-l2",
		"+l2 changed",
		" l3",
		" l4",
		" l5",
		"@@ -8,5 +8,5 @@",
		" l8",
		" l9",
		" l10",
		"-l11",
		"+l11 changed",
		" l12",
	}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Errorf("got:\n%s\n\nwant:\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
}

// Two changes close enough that their context overlaps belong in one hunk,
// exactly where diff(1) merges them.
func TestUnifiedDiffMergesNearbyHunks(t *testing.T) {
	a := strings.Split("1\n2\n3\n4\n5\n6\n7\n8\n9\n10", "\n")
	b := append([]string{}, a...)
	b[0] = "one"
	b[6] = "seven"

	got, _ := unifiedDiff(a, b, 3)
	hunks := 0
	for _, l := range got {
		if strings.HasPrefix(l, "@@") {
			hunks++
		}
	}
	if hunks != 1 {
		t.Errorf("want 1 merged hunk, got %d:\n%s", hunks, strings.Join(got, "\n"))
	}
}

func TestUnifiedDiffDeclinesHugeInputs(t *testing.T) {
	big := make([]string, 3000)
	for i := range big {
		big[i] = "x"
	}
	if _, ok := unifiedDiff(big, big, 3); ok {
		t.Error("want the quadratic table declined for a 3000x3000 input")
	}
}

// Org reads `*` and `#+` at the start of a block line as structure, including
// after indentation, which is where pandoc puts the comma too.
func TestEscOrgBlock(t *testing.T) {
	in := "plain\n* star\n  * indented\n\t#+kw\n,already\nmid * star"
	want := "plain\n,* star\n  ,* indented\n\t,#+kw\n,already\nmid * star"
	if got := escOrgBlock(in); got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestFenceForOutgrowsBackticks(t *testing.T) {
	for _, c := range []struct {
		body string
		want string
	}{
		{"plain", "```"},
		{"a ` b", "```"},
		{"```\nnested\n```", "````"},
		{"`````", "``````"},
	} {
		if got := fenceFor(c.body); got != c.want {
			t.Errorf("fenceFor(%q) = %q, want %q", c.body, got, c.want)
		}
	}
}

func TestSnippetText(t *testing.T) {
	cases := []struct{ in, want string }{
		{"<command-name>/clear</command-name> <command-message>clear</command-message> <command-args></command-args>", "/clear"},
		{"<system-reminder>ignore me</system-reminder>", ""},
		{"real question here", "real question here"},
		{"<command-name>/loop</command-name>\nand then some prose", "/loop and then some prose"},
		{"Caveat: The messages below were generated by the user.\nactual text", "actual text"},
	}
	for _, c := range cases {
		if got := snippetText(c.in); got != c.want {
			t.Errorf("snippetText(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestOrgBlockUsesExampleWithoutLanguage(t *testing.T) {
	if got := orgBlock("", "x"); got != "#+begin_example\nx\n#+end_example" {
		t.Errorf("got %q", got)
	}
	if got := orgBlock("zsh", "x"); got != "#+begin_src zsh\nx\n#+end_src" {
		t.Errorf("got %q", got)
	}
}

func TestShortModel(t *testing.T) {
	for _, c := range []struct{ in, want string }{
		{"claude-opus-5", "opus-5"},
		{"claude-fable-5", "fable-5"},
		{"claude-sonnet-5", "sonnet-5"},
		{"claude-haiku-4-5-20251001", "haiku-4.5"},
		{"<synthetic>", "synthetic"},
		{"", ""},
		{"something-unexpected", "something-unexpected"},
	} {
		if got := shortModel(c.in); got != c.want {
			t.Errorf("shortModel(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}
